### ISSUE TITLE
About your issue in Routenet challenge

### ISSUE THREAD

**Issue by ssk-28** [youchangxin/CNN_Models_TensorFlow2#1]
I apologize that I am writing the issue where it should not be but I was not able to get your email id on your github profile. 
I wanted to know that when you executed the code in Routenet challenge, you got the output delay -1 all over but then you solved it. Please guide me over how to solve this issue.(how did you denormalize the data?)

**Comment by youchangxin** [comment]
It doesn't matter, would you mind contacting me by email （chauncey.you@qq.com）
